import type { Internship } from './types';

export const internships: Internship[] = [
  {
    id: '1',
    title: 'Product Manager Intern',
    company: 'Innovate Inc.',
    description:
      'Work with our product team to define, build, and ship new features. This is a great opportunity to learn about product management in a fast-paced environment.',
    location: 'Bengaluru, India',
    sector: 'Technology',
    skills: ['Product Management', 'Agile', 'JIRA', 'User Research', 'Data Analysis'],
  },
  {
    id: '2',
    title: 'AI/ML Intern',
    company: 'DataDriven Corp.',
    description:
      'Join our AI team to work on cutting-edge machine learning models. You will be responsible for data preprocessing, model training, and evaluation.',
    location: 'Hyderabad, India',
    sector: 'Artificial Intelligence',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Data Science'],
  },
  {
    id: '3',
    title: 'Frontend Developer Intern',
    company: 'Creative Solutions',
    description:
      'Help build beautiful and responsive user interfaces for our web applications. You will work with React, Next.js, and Tailwind CSS.',
    location: 'Remote',
    sector: 'Web Development',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'HTML/CSS'],
  },
  {
    id: '4',
    title: 'Marketing Intern',
    company: 'Growth Gurus',
    description:
      'Assist in developing and executing marketing campaigns across various channels. Analyze campaign performance and suggest improvements.',
    location: 'Pune, India',
    sector: 'Marketing',
    skills: ['SEO', 'Content Marketing', 'Social Media', 'Google Analytics'],
  },
  {
    id: '5',
    title: 'Data Analyst Intern',
    company: 'NumberCrunchers',
    description:
      'Analyze large datasets to extract meaningful insights. Create dashboards and reports to communicate findings to stakeholders.',
    location: 'Chennai, India',
    sector: 'Data Analytics',
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics'],
  },
  {
    id: '6',
    title: 'UX/UI Design Intern',
    company: 'Pixel Perfect',
    description:
      'Create wireframes, mockups, and prototypes for our mobile and web products. Conduct user research and usability testing.',
    location: 'Remote',
    sector: 'Design',
    skills: ['Figma', 'Sketch', 'Adobe XD', 'User-Centered Design', 'Prototyping'],
  },
  {
    id: '7',
    title: 'Backend Developer Intern',
    company: 'ServerSide Strong',
    description: 'Work on our core backend services, APIs, and databases. Opportunity to work with Node.js, Express, and PostgreSQL.',
    location: 'Mumbai, India',
    sector: 'Software Engineering',
    skills: ['Node.js', 'Express.js', 'REST APIs', 'SQL', 'Docker'],
  },
  {
    id: '8',
    title: 'Cybersecurity Intern',
    company: 'SecureNet',
    description: 'Assist in monitoring our network for security threats, conducting vulnerability assessments, and implementing security best practices.',
    location: 'Delhi, India',
    sector: 'Cybersecurity',
    skills: ['Network Security', 'Penetration Testing', 'Firewalls', 'SIEM'],
  },
  {
    id: '9',
    title: 'Cloud Engineer Intern',
    company: 'CloudWorks',
    description: 'Help design, build, and maintain our cloud infrastructure on AWS. You will learn about cloud services, automation, and infrastructure as code.',
    location: 'Gurugram, India',
    sector: 'Cloud Computing',
    skills: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'CI/CD'],
  },
  {
    id: '10',
    title: 'DevOps Intern',
    company: 'DeployFast',
    description: 'Work with our DevOps team to improve our build and release pipelines. Focus on automation, monitoring, and infrastructure reliability.',
    location: 'Remote',
    sector: 'DevOps',
    skills: ['Jenkins', 'Ansible', 'Git', 'Scripting (Bash/Python)', 'Monitoring'],
  },
  {
    id: '11',
    title: 'Business Analyst Intern',
    company: 'Strategic Insights',
    description: 'Gather and analyze business requirements, and translate them into functional specifications for our development teams.',
    location: 'Hyderabad, India',
    sector: 'Business',
    skills: ['Business Analysis', 'Requirement Gathering', 'Agile', 'SQL'],
  },
  {
    id: '12',
    title: 'Human Resources Intern',
    company: 'PeopleFirst',
    description: 'Support the HR team with recruitment, onboarding, and employee engagement initiatives. A great role to learn the ins and outs of HR.',
    location: 'Chennai, India',
    sector: 'Human Resources',
    skills: ['Recruiting', 'Onboarding', 'HRIS', 'Communication'],
  },
  {
    id: '13',
    title: 'Sales Development Intern',
    company: 'Revenue Rockets',
    description: 'Learn to identify and qualify new sales leads, and support the sales team in achieving their targets. You will gain experience with CRM software and sales techniques.',
    location: 'Pune, India',
    sector: 'Sales',
    skills: ['Salesforce', 'Lead Generation', 'Communication', 'Negotiation'],
  },
  {
    id: '14',
    title: 'Full Stack Developer Intern',
    company: 'CodeCrafters',
    description: 'Get hands-on experience with both front-end and back-end development. You will contribute to the entire software development lifecycle.',
    location: 'Remote',
    sector: 'Web Development',
    skills: ['JavaScript', 'React', 'Node.js', 'Express.js', 'MongoDB'],
  },
  {
    id: '15',
    title: 'Software Development Engineer (SDE) Intern',
    company: 'LogicLeap',
    description: 'Join a dynamic team of engineers to design, develop, and test software solutions. This role offers exposure to a wide range of technologies and problem-solving scenarios.',
    location: 'Bengaluru, India',
    sector: 'Software Engineering',
    skills: ['Java', 'Python', 'Data Structures', 'Algorithms', 'Git'],
  },
];
